# Form implementation generated from reading ui file 'CSPR_WEFE_MM.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(152, 258)
        MainWindow.setStyleSheet("QWidget {\n"
"    font: 11pt \"Poppins\";\n"
"    background:#121212;\n"
"    color:rgb(255,255,255);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QSlider {min-height:200px;}\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTextEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QTextEdit {\n"
"    border:none;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(12, 12, 12,50);\n"
"    border: 1px solid  rgb(129, 179, 234);\n"
"    border-radius: 5px;\n"
"    padding:4px;\n"
"    text-align: left;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QTimeEdit, QDoubleSpinBox, QSpinBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QDoubleSpinBox,\n"
"QSpinBox {\n"
"    border:none;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QLabel\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QLabel {\n"
"    background:transparent;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QComboBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QComboBox {\n"
"    background-color: transparent; border:1px inset rgb(28,32,23); border-radius:2px; padding: 3px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"    QLineEdit {\n"
"    border:none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QCheckBox::indicator {\n"
"    font-weight:bold;\n"
"    background-color: transparent;\n"
"    border: 2px solid rgb(255,255,255);\n"
"    border-radius: 6px;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    margin-left:8px;\n"
"    margin-right:8px;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid white;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: rgb(255,255,255);\n"
"    border: 2px solid rgb(255,255,255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"QSlider\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider:horizontal {\n"
"    background:transparent;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 14px;\n"
"    margin: 0px;\n"
"    background:transparent;\n"
"    }\n"
"\n"
"QSlider::groove:horizontal:hover {\n"
"    background: rgb(38, 38, 38);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(255, 255, 255);\n"
"    height: 17px;\n"
"    width: 15px;\n"
"    margin: 0px;\n"
"    border-radius:7px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background:transparent;\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: white;\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color:white;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////\n"
"Time/DateEdit\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QTimeEdit,\n"
"QDateEdit {\n"
"    background-color: transparent;\n"
"    border:None;\n"
"}\n"
"\n"
"/* //////////////////////////////////////////////////////////////////////////////\n"
"QTableView\n"
"////////////////////////////////////////////////////////////////////////////// */\n"
"QTableView {\n"
"    background-color: transparent;\n"
"    alternate-background-color: rgb(101, 147, 128);\n"
"    selection-background-color: #7e57c2;\n"
"    gridline-color: rgb(90, 90, 90);color:rgb(245,245,245);\n"
"}\n"
"\n"
"QTableView::item {\n"
"    padding: 1px;\n"
"    background:rgb(216,79,79);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: #fff;\n"
"    background:rgb(23, 23, 23);\n"
"}\n"
"\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////////////////////////////\n"
"                                    QScrollBar\n"
"//////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background:transparent;\n"
"    height: 12px;\n"
"    margin: 0px 10px 0px 10px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(35,35,37);\n"
"    min-width:24px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color:transparent;\n"
"    width: 12px;\n"
"    margin: 10px 0px 10px 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(35,35,37);\n"
"    min-height: 12px;\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: transparent;\n"
"}\n"
"\n"
"\n"
"/*\n"
"VERTICAL\n"
"///////////////////////////////////////////////////////////////////////////// */\n"
"QSlider::groove:vertical {\n"
"    border-radius: 11px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    background-color: rgba(33,33,33,100);\n"
"}\n"
"\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgba(44,44,44,100);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(255, 88, 71);\n"
"    border: none;\n"
"    height: 22px;\n"
"    width: 22px;\n"
"    margin: 0px;\n"
"    border-radius: 11px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mm_page = QtWidgets.QWidget()
        self.mm_page.setObjectName("mm_page")
        self.gridLayout = QtWidgets.QGridLayout(self.mm_page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.mm_container = QtWidgets.QFrame(parent=self.mm_page)
        self.mm_container.setObjectName("mm_container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mm_container)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mixed_risk_slider = QtWidgets.QSlider(parent=self.mm_container)
        self.mixed_risk_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.mixed_risk_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(220,99,108);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(220,99,108);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(222,100,109);}\n"
"QSlider::handle:vertical:hover {background:rgb(252,130,139);}\n"
"QSlider::handle:vertical:pressed {background:rgb(202,80,89);}\n"
"QSlider::add-page:vertical{background:rgb(222,100,109);}\n"
"QSlider::groove:vertical:hover {background:rgba(222,100,109,0.35);}\n"
"QSlider::groove:vertical {background:rgba(222,100,109,0.15);}")
        self.mixed_risk_slider.setMaximum(10)
        self.mixed_risk_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.mixed_risk_slider.setObjectName("mixed_risk_slider")
        self.gridLayout_2.addWidget(self.mixed_risk_slider, 0, 3, 1, 1)
        self.mood_slider = QtWidgets.QSlider(parent=self.mm_container)
        self.mood_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.mood_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(104,174,102);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(104,174,102);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"QSlider::handle:vertical {background:rgb(96,175,107);}\n"
"QSlider::handle:vertical:hover {background:rgb(126,205,137);}\n"
"QSlider::handle:vertical:pressed {background:rgb(76,155,87);}\n"
"QSlider::add-page:vertical {background:rgb(96,175,107);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,175,107,0.35);}\n"
"QSlider::groove:vertical {background:rgba(96,175,107,0.15);}\n"
"")
        self.mood_slider.setMaximum(10)
        self.mood_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.mood_slider.setObjectName("mood_slider")
        self.gridLayout_2.addWidget(self.mood_slider, 0, 0, 1, 1)
        self.mania = QtWidgets.QSpinBox(parent=self.mm_container)
        self.mania.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(184,153,222);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(184,153,222);\n"
"}\n"
"\n"
"\n"
"\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QSpinBox\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QSpinBox {color:rgb(220,180,74);}\n"
"    QSpinBox:hover {color: rgb(255,240,134);}\n"
"    QSpinBox:focus {color: rgb(250,210,104);}\n"
"    ")
        self.mania.setFrame(False)
        self.mania.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.mania.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mania.setMaximum(10)
        self.mania.setObjectName("mania")
        self.gridLayout_2.addWidget(self.mania, 1, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.depression_slider = QtWidgets.QSlider(parent=self.mm_container)
        self.depression_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.depression_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(93,112,219);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(93,112,219);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"depression slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"QSlider::handle:vertical {background:rgb(87,111,215);}\n"
"QSlider::handle:vertical:hover {background:rgb(117,141,245);}\n"
"QSlider::handle:vertical:pressed {background:rgb(67,91,195);}\n"
"QSlider::add-page:vertical {background:rgb(87,111,215);}\n"
"QSlider::groove:vertical:hover{background:rgba(87,111,215,0.35);}\n"
"\n"
"QSlider::groove:vertical {background:rgba(87,111,215,0.15);}")
        self.depression_slider.setMaximum(10)
        self.depression_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.depression_slider.setObjectName("depression_slider")
        self.gridLayout_2.addWidget(self.depression_slider, 0, 2, 1, 1)
        self.mania_slider = QtWidgets.QSlider(parent=self.mm_container)
        self.mania_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.mania_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(249,195,94);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(249,195,94);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSlider Colors\n"
"/////////////////////////////////////////////////////////////// */\n"
"\n"
"\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QSlider Colors\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    \n"
"QSlider::handle:vertical {background:rgb(220,180,74);}\n"
"QSlider::handle:vertical:hover {background:rgb(250,210,104);}\n"
"QSlider::handle:vertical:pressed {background:rgb(200,160,54);}\n"
"QSlider::add-page:vertical {background:rgb(220,180,74);}\n"
"QSlider::groove:vertical:hover {background:rgba(220,180,74,0.35);}\n"
"QSlider::groove:vertical {background:rgba(220,180,74,0.15);}\n"
"    ")
        self.mania_slider.setMaximum(10)
        self.mania_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.mania_slider.setObjectName("mania_slider")
        self.gridLayout_2.addWidget(self.mania_slider, 0, 1, 1, 1)
        self.depression = QtWidgets.QSpinBox(parent=self.mm_container)
        self.depression.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(93,112,219);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(93,112,219);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(87,111,215);background:transparent;}\n"
"QSpinBox:hover {color: rgb(147,171,255);}\n"
"QSpinBox:focus {color: rgb(117,141,245);}\n"
"")
        self.depression.setFrame(False)
        self.depression.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.depression.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.depression.setMaximum(10)
        self.depression.setObjectName("depression")
        self.gridLayout_2.addWidget(self.depression, 1, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.mood = QtWidgets.QSpinBox(parent=self.mm_container)
        self.mood.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(104,174,102);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(104,174,102);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {background:transparent;color:rgb(96,175,107);}\n"
"QSpinBox:hover {color: rgb(156,235,167);}\n"
"QSpinBox:focus {color: rgb(126,205,137);}\n"
"")
        self.mood.setFrame(False)
        self.mood.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.mood.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mood.setMaximum(10)
        self.mood.setObjectName("mood")
        self.gridLayout_2.addWidget(self.mood, 1, 0, 1, 1)
        self.mixed_risk = QtWidgets.QSpinBox(parent=self.mm_container)
        self.mixed_risk.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(220,99,108);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(220,99,108);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {color:rgb(222,100,109);}\n"
"QSpinBox:hover {color: rgb(255,160,169);}\n"
"QSpinBox:focus {color: rgb(252,130,139);}\n"
"")
        self.mixed_risk.setFrame(False)
        self.mixed_risk.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.mixed_risk.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.mixed_risk.setMaximum(10)
        self.mixed_risk.setObjectName("mixed_risk")
        self.gridLayout_2.addWidget(self.mixed_risk, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.mm_container, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.mm_page)
        self.wefe_page = QtWidgets.QWidget()
        self.wefe_page.setObjectName("wefe_page")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.wefe_page)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.wefe_container = QtWidgets.QFrame(parent=self.wefe_page)
        self.wefe_container.setObjectName("wefe_container")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wefe_container)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setHorizontalSpacing(0)
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.wefe_container)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.wellbeing_spinbox = QtWidgets.QSpinBox(parent=self.frame)
        self.wellbeing_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(184,153,222);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(184,153,222);\n"
"}\n"
"\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QSpinBox\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QSpinBox {color:rgb(186,153,219);}\n"
"    QSpinBox:hover {color: rgb(246,213,255);}\n"
"    QSpinBox:focus {color: rgb(216,183,249);}\n"
"    ")
        self.wellbeing_spinbox.setFrame(False)
        self.wellbeing_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.wellbeing_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.wellbeing_spinbox.setMaximum(10)
        self.wellbeing_spinbox.setObjectName("wellbeing_spinbox")
        self.verticalLayout_5.addWidget(self.wellbeing_spinbox)
        self.gridLayout_4.addWidget(self.frame, 2, 0, 1, 1)
        self.focus_spinbox = QtWidgets.QSpinBox(parent=self.wefe_container)
        self.focus_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(100,172,173);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(100,172,173);\n"
"}\n"
"QSpinBox {background:transparent;color:rgb(89,172,172);}\n"
"QSpinBox:hover {color: rgb(149,232,232);}\n"
"QSpinBox:focus {color: rgb(119,202,202);}\n"
"")
        self.focus_spinbox.setFrame(False)
        self.focus_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.focus_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.focus_spinbox.setMaximum(10)
        self.focus_spinbox.setObjectName("focus_spinbox")
        self.gridLayout_4.addWidget(self.focus_spinbox, 2, 2, 1, 1)
        self.focus_slider = QtWidgets.QSlider(parent=self.wefe_container)
        self.focus_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.focus_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(100,172,173);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(100,172,173);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"focus slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"QSlider::handle:vertical {background:rgb(89,172,172);}\n"
"QSlider::groove:vertical{background:rgba(89,172,172, 15);}\n"
"QSlider::handle:vertical:hover {background:rgb(119,202,202);}\n"
"QSlider::handle:vertical:pressed {background:rgb(69,152,152);}\n"
"QSlider::add-page:vertical{background:rgb(89,172,172);}\n"
"QSlider::groove:vertical:hover {background:rgba(89,172,172,0.35);}")
        self.focus_slider.setMaximum(10)
        self.focus_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.focus_slider.setObjectName("focus_slider")
        self.gridLayout_4.addWidget(self.focus_slider, 0, 2, 2, 1)
        self.energy_spinbox = QtWidgets.QSpinBox(parent=self.wefe_container)
        self.energy_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(104,174,102);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(104,174,102);\n"
"}\n"
"\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QSpinBox\n"
"/////////////////////////////////////////////////////////////// */\n"
"QSpinBox {background:transparent;color:rgb(96,175,107);}\n"
"QSpinBox:hover {color: rgb(156,235,167);}\n"
"QSpinBox:focus {color: rgb(126,205,137);}\n"
"")
        self.energy_spinbox.setFrame(False)
        self.energy_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.energy_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.energy_spinbox.setMaximum(10)
        self.energy_spinbox.setObjectName("energy_spinbox")
        self.gridLayout_4.addWidget(self.energy_spinbox, 2, 3, 1, 1)
        self.energy_slider = QtWidgets.QSlider(parent=self.wefe_container)
        self.energy_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.energy_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(104,174,102);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(104,174,102);\n"
"}\n"
"\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"energy slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"QSlider::handle:vertical {background:rgb(96,174,106);}\n"
"QSlider::groove:vertical {background:rgba(96,174,106, 15);}\n"
"QSlider::handle:vertical:hover {background:rgb(126,204,136);}\n"
"QSlider::handle:vertical:pressed {background:rgb(76,154,86);}\n"
"QSlider::add-page:vertical {background:rgb(96,174,106);}\n"
"QSlider::groove:vertical:hover {background:rgba(96,174,106,0.35);}\n"
"")
        self.energy_slider.setMaximum(10)
        self.energy_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.energy_slider.setObjectName("energy_slider")
        self.gridLayout_4.addWidget(self.energy_slider, 0, 3, 2, 1)
        self.excite_spinbox = QtWidgets.QSpinBox(parent=self.wefe_container)
        self.excite_spinbox.setStyleSheet("\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QSpinBox\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    QSpinBox {color:rgb(122,177,222);}\n"
"    QSpinBox:hover {color: rgb(182,237,255);}\n"
"    QSpinBox:focus {color: rgb(152,207,252);}\n"
"    ")
        self.excite_spinbox.setFrame(False)
        self.excite_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.excite_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.excite_spinbox.setMaximum(10)
        self.excite_spinbox.setObjectName("excite_spinbox")
        self.gridLayout_4.addWidget(self.excite_spinbox, 2, 1, 1, 1)
        self.wellbeing_slider = QtWidgets.QSlider(parent=self.wefe_container)
        self.wellbeing_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.wellbeing_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(184,153,222);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(184,153,222);\n"
"}\n"
"QSlider::groove:vertical {background:rgba(186,153,219, 15);}\n"
"QSlider::handle:vertical {background:rgb(186,153,219);}\n"
"QSlider::handle:vertical:hover {background:rgb(216,183,249);}\n"
"QSlider::handle:vertical:pressed {background:rgb(166,133,199);}\n"
"QSlider::add-page:vertical{background:rgb(186,153,219);}\n"
"QSlider::groove:vertical:hover {background:rgba(186,153,219,35);}\n"
"")
        self.wellbeing_slider.setMaximum(10)
        self.wellbeing_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.wellbeing_slider.setObjectName("wellbeing_slider")
        self.gridLayout_4.addWidget(self.wellbeing_slider, 0, 0, 2, 1)
        self.excite_slider = QtWidgets.QSlider(parent=self.wefe_container)
        self.excite_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.excite_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(100,172,173);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(100,172,173);\n"
"}\n"
"\n"
"    /* ///////////////////////////////////////////////////////////////\n"
"    QSlider Colors\n"
"    /////////////////////////////////////////////////////////////// */\n"
"    \n"
"    QSlider::handle:vertical {background:rgb(122,177,222);}\n"
"    QSlider::groove:vertical{background:rgba(122,177,222, 15);}\n"
"    QSlider::handle:vertical:hover {background:rgb(152,207,252);}\n"
"    QSlider::handle:vertical:pressed {background:rgb(102,157,202);}\n"
"    QSlider::add-page:vertical{background:rgb(122,177,222);}\n"
"    QSlider::groove:vertical:hover {background:rgba(122,177,222,35);}\n"
"    ")
        self.excite_slider.setMaximum(10)
        self.excite_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.excite_slider.setObjectName("excite_slider")
        self.gridLayout_4.addWidget(self.excite_slider, 0, 1, 2, 1)
        self.gridLayout_6.addWidget(self.wefe_container, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.wefe_page)
        self.cspr_page = QtWidgets.QWidget()
        self.cspr_page.setObjectName("cspr_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.cspr_page)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cspr_container = QtWidgets.QFrame(parent=self.cspr_page)
        self.cspr_container.setObjectName("cspr_container")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.cspr_container)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rage_spinbox = QtWidgets.QSpinBox(parent=self.cspr_container)
        self.rage_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(220,99,108);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(220,99,108);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"rage spinbox\n"
" //////////////////////////////////////////////////////////////////////// */\n"
"#rage_spinbox {background:transparent;color:rgb(229,100,111);}\n"
"#rage_spinbox:hover {color: rgb(255,160,171);}\n"
"#rage_spinbox:focus {color: rgb(255,130,141);}")
        self.rage_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rage_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.rage_spinbox.setMaximum(10)
        self.rage_spinbox.setObjectName("rage_spinbox")
        self.gridLayout_3.addWidget(self.rage_spinbox, 1, 3, 1, 1)
        self.rage_slider = QtWidgets.QSlider(parent=self.cspr_container)
        self.rage_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.rage_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(220,99,108);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(220,99,108);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"rage slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"#rage_slider::handle:vertical {background:rgb(229,100,111);}\n"
"#rage_slider::handle:vertical:hover {background:rgb(255,130,141);}\n"
"#rage_slider::handle:vertical:pressed {background:rgb(209,80,91);}\n"
"#rage_slider::add-page:vertical {background:rgb(229,100,111);}\n"
"#rage_slider::groove:vertical:hover {background:rgba(229,100,111,0.35);}\n"
"#rage_slider::groove:vertical {background:rgba(229,100,111,0.15);}")
        self.rage_slider.setMaximum(10)
        self.rage_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.rage_slider.setObjectName("rage_slider")
        self.gridLayout_3.addWidget(self.rage_slider, 0, 3, 1, 1)
        self.pain_spinbox = QtWidgets.QSpinBox(parent=self.cspr_container)
        self.pain_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(223,134,93);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(223,134,93);\n"
"}\n"
"\n"
"#pain_spinbox {color:rgb(229,133,98);}\n"
"#pain_spinbox:hover {color: rgb(255,193,158);}\n"
"#pain_spinbox:focus {color: rgb(255,163,128);}\n"
"")
        self.pain_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pain_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.pain_spinbox.setMaximum(10)
        self.pain_spinbox.setObjectName("pain_spinbox")
        self.gridLayout_3.addWidget(self.pain_spinbox, 1, 2, 1, 1)
        self.pain_slider = QtWidgets.QSlider(parent=self.cspr_container)
        self.pain_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.pain_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(223,134,93);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(223,134,93);\n"
"}\n"
"/* Pain Slider */\n"
"#pain_slider::handle:vertical {background:rgb(229,133,98);}\n"
"#pain_slider::handle:vertical:hover {background:rgb(255,163,128);}\n"
"#pain_slider::handle:vertical:pressed {background:rgb(209,113,78);}\n"
"#pain_slider::add-page:vertical {background:rgb(229,133,98);}\n"
"#pain_slider::groove:vertical:hover {background:rgba(229,133,98,0.35);}\n"
"#pain_slider::groove:vertical {background:rgba(229,133,98,0.15);}")
        self.pain_slider.setMaximum(10)
        self.pain_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.pain_slider.setObjectName("pain_slider")
        self.gridLayout_3.addWidget(self.pain_slider, 0, 2, 1, 1)
        self.calm_slider = QtWidgets.QSlider(parent=self.cspr_container)
        self.calm_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.calm_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(125,123,202);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(125,123,202);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"calm slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"#calm_slider::handle:vertical {background:rgb(123,123,199);}\n"
"#calm_slider::handle:vertical:hover {background:rgb(153,153,229);}\n"
"#calm_slider::handle:vertical:pressed {background:rgb(103,103,179);}\n"
"#calm_slider::add-page:vertical {background:rgb(123,123,199);}\n"
"#calm_slider::groove:vertical:hover {background:rgba(123,123,199,0.35);}\n"
"#calm_slider::groove:vertical {background:rgba(123,123,199,0.15);}")
        self.calm_slider.setMaximum(10)
        self.calm_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.calm_slider.setObjectName("calm_slider")
        self.gridLayout_3.addWidget(self.calm_slider, 0, 0, 1, 1)
        self.calm_spinbox = QtWidgets.QSpinBox(parent=self.cspr_container)
        self.calm_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(125,123,202);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(125,123,202);\n"
"}\n"
"#calm_spinbox{color:rgb(123,123,199);}\n"
"#calm_spinbox:hover {color: rgb(183,183,255);}\n"
"#calm_spinbox:focus {color: rgb(153,153,229);}\n"
"")
        self.calm_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.calm_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.calm_spinbox.setMaximum(10)
        self.calm_spinbox.setObjectName("calm_spinbox")
        self.gridLayout_3.addWidget(self.calm_spinbox, 1, 0, 1, 1)
        self.stress_spinbox = QtWidgets.QSpinBox(parent=self.cspr_container)
        self.stress_spinbox.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(249,195,94);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(249,195,94);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"Stress\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"#stress_spinbox {background:transparent;color:rgb(254,195,105);}\n"
"#stress_spinbox:hover {color: rgb(255,255,165);}\n"
"#stress_spinbox:focus {color: rgb(255,225,135); }")
        self.stress_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.stress_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.stress_spinbox.setAccelerated(True)
        self.stress_spinbox.setMaximum(10)
        self.stress_spinbox.setObjectName("stress_spinbox")
        self.gridLayout_3.addWidget(self.stress_spinbox, 1, 1, 1, 1)
        self.stress_slider = QtWidgets.QSlider(parent=self.cspr_container)
        self.stress_slider.setMinimumSize(QtCore.QSize(28, 200))
        self.stress_slider.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(249,195,94);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(249,195,94);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"stress slider\n"
"//////////////////////////////////////////////////////////////////////// */\n"
"#stress_slider::handle:vertical {background:rgb(254,195,105);}\n"
"#stress_slider::handle:vertical:hover {background:rgb(255,225,135);}\n"
"#stress_slider::handle:vertical:pressed {background:rgb(234,175,85);}\n"
"#stress_slider::add-page:vertical {background:rgb(254,195,105);}\n"
"#stress_slider::groove:vertical:hover {background:rgba(254,195,105,0.35);}\n"
"#stress_slider::groove:vertical {background:rgba(254,195,105,0.15);}\n"
"")
        self.stress_slider.setMaximum(10)
        self.stress_slider.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.stress_slider.setObjectName("stress_slider")
        self.gridLayout_3.addWidget(self.stress_slider, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.cspr_container, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.cspr_page)
        self.data_page = QtWidgets.QWidget()
        self.data_page.setObjectName("data_page")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.data_page)
        self.gridLayout_7.setContentsMargins(0, 0, -1, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.data_page)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"background-color: #fff;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;    \n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"margin-left:9px;\n"
"padding-top:2px;\n"
"padding-bottom:2px;\n"
"background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background-color: transparent;\n"
"font-weight:bold;\n"
"font-size:8pt;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    border-radius: 4px;\n"
"    \n"
"}\n"
"\n"
"QTabBar::tab:only-one {\n"
"background-color: transparent;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame1 = QtWidgets.QFrame(parent=self.tab_2)
        self.frame1.setObjectName("frame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.mental_mental_table = QtWidgets.QTableView(parent=self.frame1)
        self.mental_mental_table.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.mental_mental_table.setSortingEnabled(True)
        self.mental_mental_table.setObjectName("mental_mental_table")
        self.mental_mental_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.mental_mental_table)
        self.gridLayout_10.addWidget(self.frame1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame2 = QtWidgets.QFrame(parent=self.tab_3)
        self.frame2.setObjectName("frame2")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame2)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(parent=self.frame2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.summing_box = QtWidgets.QSpinBox(parent=self.frame2)
        self.summing_box.setStyleSheet("\n"
"/* ///////////////////////////////////////////////////////////////\n"
"QToolTip\n"
"/////////////////////////////////////////////////////////////// */\n"
"QToolTip {\n"
"    background: rgba(23,23,23, 150);\n"
"    border: 1px solid rgb(220,99,108);\n"
"    border-radius: 5px; \n"
"    padding:4px; \n"
"    text-align: left;\n"
"    color: rgb(220,99,108);\n"
"}\n"
"/* ////////////////////////////////////////////////////////////////////////\n"
"rage spinbox\n"
" //////////////////////////////////////////////////////////////////////// */\n"
"QSpinBox {background:transparent;color:rgb(229,100,111);}\n"
"QSpinBox:hover {color: rgb(255,160,171);}\n"
"QSpinBox:focus {color: rgb(255,130,141);}")
        self.summing_box.setFrame(False)
        self.summing_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.summing_box.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.summing_box.setMaximum(40)
        self.summing_box.setObjectName("summing_box")
        self.gridLayout_12.addWidget(self.summing_box, 1, 0, 1, 1)
        self.wefe_tableview = QtWidgets.QTableView(parent=self.frame2)
        self.wefe_tableview.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.wefe_tableview.setSortingEnabled(True)
        self.wefe_tableview.setObjectName("wefe_tableview")
        self.wefe_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_12.addWidget(self.wefe_tableview, 2, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame3 = QtWidgets.QFrame(parent=self.tab)
        self.frame3.setObjectName("frame3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame3)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.cspr_tableview = QtWidgets.QTableView(parent=self.frame3)
        self.cspr_tableview.setStyleSheet("\n"
"QTableView {\n"
"background-color: transparent;\n"
"selection-background-color: #7e57c2;\n"
"gridline-color:transparent;\n"
"color: rgb(77, 15, 26);\n"
"}\n"
"QTableView::item {\n"
"padding: 1px;color: rgb(77, 15, 26);\n"
"background:rgb(229,100,111);\n"
"}\n"
"QTableView::item:selected {\n"
"    color: rgb(255, 255, 255);\n"
"background:rgb(23, 23, 23);\n"
"}\n"
"    ")
        self.cspr_tableview.setSortingEnabled(True)
        self.cspr_tableview.setObjectName("cspr_tableview")
        self.cspr_tableview.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_11.addWidget(self.cspr_tableview, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_11.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_9.addWidget(self.frame3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_7.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.data_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.wefe_frame = QtWidgets.QFrame(parent=self.page)
        self.wefe_frame.setObjectName("wefe_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wefe_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.wefe_date = QtWidgets.QDateEdit(parent=self.wefe_frame)
        self.wefe_date.setObjectName("wefe_date")
        self.verticalLayout_4.addWidget(self.wefe_date)
        self.wefe_time = QtWidgets.QTimeEdit(parent=self.wefe_frame)
        self.wefe_time.setObjectName("wefe_time")
        self.verticalLayout_4.addWidget(self.wefe_time)
        self.verticalLayout_7.addWidget(self.wefe_frame)
        self.cspr_frame = QtWidgets.QFrame(parent=self.page)
        self.cspr_frame.setObjectName("cspr_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cspr_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cspr_date = QtWidgets.QDateEdit(parent=self.cspr_frame)
        self.cspr_date.setObjectName("cspr_date")
        self.verticalLayout_3.addWidget(self.cspr_date)
        self.cspr_time = QtWidgets.QTimeEdit(parent=self.cspr_frame)
        self.cspr_time.setObjectName("cspr_time")
        self.verticalLayout_3.addWidget(self.cspr_time)
        self.verticalLayout_7.addWidget(self.cspr_frame)
        self.mm_frame = QtWidgets.QFrame(parent=self.page)
        self.mm_frame.setObjectName("mm_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mm_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mental_mental_date = QtWidgets.QDateEdit(parent=self.mm_frame)
        self.mental_mental_date.setObjectName("mental_mental_date")
        self.verticalLayout_2.addWidget(self.mental_mental_date)
        self.mental_mental_time = QtWidgets.QTimeEdit(parent=self.mm_frame)
        self.mental_mental_time.setObjectName("mental_mental_time")
        self.verticalLayout_2.addWidget(self.mental_mental_time)
        self.verticalLayout_7.addWidget(self.mm_frame)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout_8.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 152, 18))
        self.menubar.setObjectName("menubar")
        self.menuMHE = QtWidgets.QMenu(parent=self.menubar)
        self.menuMHE.setObjectName("menuMHE")
        self.menuDATA = QtWidgets.QMenu(parent=self.menubar)
        self.menuDATA.setObjectName("menuDATA")
        self.menuVIEWS = QtWidgets.QMenu(parent=self.menubar)
        self.menuVIEWS.setObjectName("menuVIEWS")
        MainWindow.setMenuBar(self.menubar)
        self.actionCommitWEFE = QtGui.QAction(parent=MainWindow)
        self.actionCommitWEFE.setObjectName("actionCommitWEFE")
        self.actionCommitCSPR = QtGui.QAction(parent=MainWindow)
        self.actionCommitCSPR.setObjectName("actionCommitCSPR")
        self.actionCommitMM = QtGui.QAction(parent=MainWindow)
        self.actionCommitMM.setObjectName("actionCommitMM")
        self.actionDelete = QtGui.QAction(parent=MainWindow)
        self.actionDelete.setObjectName("actionDelete")
        self.actionShowWEFE = QtGui.QAction(parent=MainWindow)
        self.actionShowWEFE.setObjectName("actionShowWEFE")
        self.actionShowCSPR = QtGui.QAction(parent=MainWindow)
        self.actionShowCSPR.setObjectName("actionShowCSPR")
        self.actionShowMM = QtGui.QAction(parent=MainWindow)
        self.actionShowMM.setObjectName("actionShowMM")
        self.actionShowData = QtGui.QAction(parent=MainWindow)
        self.actionShowData.setObjectName("actionShowData")
        self.menuDATA.addAction(self.actionCommitWEFE)
        self.menuDATA.addAction(self.actionCommitCSPR)
        self.menuDATA.addAction(self.actionCommitMM)
        self.menuDATA.addAction(self.actionDelete)
        self.menuVIEWS.addAction(self.actionShowWEFE)
        self.menuVIEWS.addAction(self.actionShowCSPR)
        self.menuVIEWS.addAction(self.actionShowMM)
        self.menuVIEWS.addAction(self.actionShowData)
        self.menubar.addAction(self.menuMHE.menuAction())
        self.menubar.addAction(self.menuDATA.menuAction())
        self.menubar.addAction(self.menuVIEWS.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.mood, self.mania)
        MainWindow.setTabOrder(self.mania, self.depression)
        MainWindow.setTabOrder(self.depression, self.mixed_risk)
        MainWindow.setTabOrder(self.mixed_risk, self.wellbeing_spinbox)
        MainWindow.setTabOrder(self.wellbeing_spinbox, self.excite_spinbox)
        MainWindow.setTabOrder(self.excite_spinbox, self.focus_spinbox)
        MainWindow.setTabOrder(self.focus_spinbox, self.energy_spinbox)
        MainWindow.setTabOrder(self.energy_spinbox, self.calm_spinbox)
        MainWindow.setTabOrder(self.calm_spinbox, self.stress_spinbox)
        MainWindow.setTabOrder(self.stress_spinbox, self.pain_spinbox)
        MainWindow.setTabOrder(self.pain_spinbox, self.rage_spinbox)
        MainWindow.setTabOrder(self.rage_spinbox, self.energy_slider)
        MainWindow.setTabOrder(self.energy_slider, self.mood_slider)
        MainWindow.setTabOrder(self.mood_slider, self.wellbeing_slider)
        MainWindow.setTabOrder(self.wellbeing_slider, self.excite_slider)
        MainWindow.setTabOrder(self.excite_slider, self.depression_slider)
        MainWindow.setTabOrder(self.depression_slider, self.rage_slider)
        MainWindow.setTabOrder(self.rage_slider, self.focus_slider)
        MainWindow.setTabOrder(self.focus_slider, self.pain_slider)
        MainWindow.setTabOrder(self.pain_slider, self.calm_slider)
        MainWindow.setTabOrder(self.calm_slider, self.mania_slider)
        MainWindow.setTabOrder(self.mania_slider, self.mixed_risk_slider)
        MainWindow.setTabOrder(self.mixed_risk_slider, self.stress_slider)
        MainWindow.setTabOrder(self.stress_slider, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.mental_mental_table)
        MainWindow.setTabOrder(self.mental_mental_table, self.summing_box)
        MainWindow.setTabOrder(self.summing_box, self.wefe_tableview)
        MainWindow.setTabOrder(self.wefe_tableview, self.cspr_tableview)
        MainWindow.setTabOrder(self.cspr_tableview, self.wefe_date)
        MainWindow.setTabOrder(self.wefe_date, self.wefe_time)
        MainWindow.setTabOrder(self.wefe_time, self.cspr_date)
        MainWindow.setTabOrder(self.cspr_date, self.cspr_time)
        MainWindow.setTabOrder(self.cspr_time, self.mental_mental_date)
        MainWindow.setTabOrder(self.mental_mental_date, self.mental_mental_time)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mixed_risk_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mixed Risk</p></body></html>"))
        self.mood_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mood</p></body></html>"))
        self.mania.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mania</p></body></html>"))
        self.depression_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Depression</p></body></html>"))
        self.mania_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mania</p></body></html>"))
        self.depression.setToolTip(_translate("MainWindow", "<html><head/><body><p>Depression</p></body></html>"))
        self.mood.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mood</p></body></html>"))
        self.mixed_risk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Mixed Risk</p></body></html>"))
        self.wellbeing_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Wellbeing</p></body></html>"))
        self.focus_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>focus</p></body></html>"))
        self.focus_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>focus</p></body></html>"))
        self.energy_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Energy</p></body></html>"))
        self.energy_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Energy</p></body></html>"))
        self.excite_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Excitement</p></body></html>"))
        self.wellbeing_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Wellbeing</p></body></html>"))
        self.excite_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Excitement</p></body></html>"))
        self.rage_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Rage</p></body></html>"))
        self.rage_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Rage</p></body></html>"))
        self.pain_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pain</p></body></html>"))
        self.pain_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Pain</p></body></html>"))
        self.calm_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calm</p></body></html>"))
        self.calm_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calm</p></body></html>"))
        self.stress_spinbox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stress</p></body></html>"))
        self.stress_slider.setToolTip(_translate("MainWindow", "<html><head/><body><p>Stress</p></body></html>"))
        self.stress_slider.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "MM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "MM"))
        self.label_3.setText(_translate("MainWindow", "WEFE"))
        self.summing_box.setToolTip(_translate("MainWindow", "<html><head/><body><p>Summing Box</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "WEFE"))
        self.label_2.setText(_translate("MainWindow", "CSPR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "CSPR"))
        self.menuMHE.setTitle(_translate("MainWindow", "MHE"))
        self.menuDATA.setTitle(_translate("MainWindow", "DATA"))
        self.menuVIEWS.setTitle(_translate("MainWindow", "VIEWS"))
        self.actionCommitWEFE.setText(_translate("MainWindow", "Commit WEFE"))
        self.actionCommitWEFE.setShortcut(_translate("MainWindow", "Meta+2"))
        self.actionCommitCSPR.setText(_translate("MainWindow", "Commit CSPR"))
        self.actionCommitCSPR.setShortcut(_translate("MainWindow", "Meta+3"))
        self.actionCommitMM.setText(_translate("MainWindow", "Commit MM"))
        self.actionCommitMM.setShortcut(_translate("MainWindow", "Meta+1"))
        self.actionDelete.setText(_translate("MainWindow", "Delete  SelecetedRecords"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionShowWEFE.setText(_translate("MainWindow", "WEFE"))
        self.actionShowWEFE.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.actionShowCSPR.setText(_translate("MainWindow", "CSPR"))
        self.actionShowCSPR.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.actionShowMM.setText(_translate("MainWindow", "MM"))
        self.actionShowMM.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.actionShowData.setText(_translate("MainWindow", "Data Views"))
        self.actionShowData.setShortcut(_translate("MainWindow", "Ctrl+4"))
